### ISSUE TITLE
Same key startup JVM Options are overwritten

### ISSUE THREAD

**Issue by CarlosMOGoncalves** [payara/ecosystem-eclipse-plugin#15]
This issue is related to #11.

When one downloads Payara 5.192, it brings a set of JVM options in domain.xml which are needed to work with JDK 11. These are the options, exactly as they are stated in domain.xml:

`<jvm-options>[9|]--add-opens=java.base/jdk.internal.loader=ALL-UNNAMED</jvm-options>`
`<jvm-options>[9|]--add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED</jvm-options>`
`<!-- Hazelcast internal package access requirement to get the best performance results. -->`
`<jvm-options>[9|]--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED</jvm-options>`
`<jvm-options>[9|]--add-opens=java.base/java.lang=ALL-UNNAMED</jvm-options>`
`<jvm-options>[9|]--add-opens=java.base/java.nio=ALL-UNNAMED</jvm-options>`
`<jvm-options>[9|]--add-opens=java.base/sun.nio.ch=ALL-UNNAMED</jvm-options>`
`<jvm-options>[9|]--add-opens=java.management/sun.management=ALL-UNNAMED</jvm-options>`
`<jvm-options>[9|]--add-opens=java.base/sun.net.www.protocol.jrt=ALL-UNNAMED</jvm-options>`

They are needed for JDK9+ compatibility reasons. However, when a Payara server is started from the Payara Tools, most of these options are not actually passed to the java executable. The server will still load, but it will complain, for example:

> 2019-08-27T11:10:29.093+0100|WARNING: Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED

After digging through the code, I figured why it is happening. The reason is the following: in **ServerTasks.java** all the JVM options (among others) need to be parsed and validated before actually calling the java program. However, the JDK9+ options, as they are written at the moment are simply overwritten here (line 357 onward): 

            for (String opt : optList) {
            // do placeholder substitution
            opt = Utils.doSub(opt.trim(), varMap);
            
            int splitIndex = opt.indexOf('=');
            
            // && !opt.startsWith("-agentpath:") is a temporary hack to
            // not touch already quoted -agentpath. Later we should handle it
            // in a better way.
            if (splitIndex != -1 && !opt.startsWith("-agentpath:")) {
                
                // key=value type of option
                
                name = opt.substring(0, splitIndex);
                value = Utils.quote(opt.substring(splitIndex + 1));
                LOGGER.log(Level.FINER, METHOD, "jvmOptVal", new Object[] { name, value });

            } else if (opt.startsWith("-Xbootclasspath")) {

                // -Xbootclasspath:<path> or -Xbootclasspath/p:<path> or -Xbootclasspath/a:<path>
                
                name = opt;
                value = null;
                
                int colonIndex = opt.indexOf(':');
                if (colonIndex != -1) {
                    String optionName = opt.substring(0, colonIndex);
                    String optonValue = Utils.quote(opt.substring(colonIndex + 1));
                    
                    name = optionName + ":" + optonValue;
                }
            } else {
                name = opt;
                value = null;
                LOGGER.log(Level.FINER, METHOD, "jvmOpt", name);
            }
            
            if (!keyValueArgs.containsKey(name)) {
                keyOrder.add(name);
            }
            keyValueArgs.put(name, value);
        }

This piece of code will look for JVM options with an "=" on them and assume they are some key/value pair. While this is true for the kind they are looking for, it doesn't play well with these options because of their syntax. The consequence is that these JDK9+ options, which are meant to be stacked up will end up being overwritten in the `Map<String,String> keyValueArgs`, as each new option with the same name replaces a previous one, resulting in an incomplete argument string to be sent to the java program. It ends up sending just 2 out of the standard 8 used in the domain.xml. While the server does start with just warnings, there is no telling whether this has impacts further down the line, but above all, it is not the correct behaviour.

Now, it is true that these options are also not correctly written. As I stated in #11, the new -add-xxx options are NOT meant to have an "=" after them (they should have embedded spaces after the --add-xx). The reason they are written like that in domain.xml is because the code that is used to start the java program in Payara (which I assume must come from Glassfish itself) does not parse those options correctly either (i.e. if they do not have equals it will just break). I will open an issue with Payara also so that you can look at that.

I suggest to review this code and ignore these options as "keyValueArgs candidates" so that they can be passed like that to the java program. The java program DOES accept the new-style JVM options even if they have equals in them (I tested it) so the plugin will run just fine whether the options have "=" or not.

Can you take a look at this? 

I will also open an issue on Payara server repository so that they can accept the new-style options and then we can clean those "=" from the domain.xml (this plugin accepts the new style because you have used a trick to pass them to the java program, if you didn't, then ProcessImpl.java from the standard java lib would quote those args and wreck the whole thing apart).

### Environment

- **Payara Tools**: 1.0.0.201906280050	(current master branch)
- **SO**: Windows 10
- **JDK**: AdoptOpenJDK 11.0.3
- **IDE**: Eclipse 2019-06
- **Payara Server**: 5.192

**Comment by jGauravGupta** [comment]
Hi @CarlosMOGoncalves , 

I have created an internal issue **EP-44** to address it.

**Comment by CarlosMOGoncalves** [comment]
Sure, will do as soon as I come from vacation.

Thanks!

**Comment by jGauravGupta** [comment]
Fixed by https://github.com/payara/ecosystem-eclipse-plugin/pull/16
