### ISSUE TITLE
On Deploy: NullPointerException, when Projects are linked but not all specified in "Deployment Assembly"

### ISSUE THREAD

**Issue by cbbravo** [payara/ecosystem-eclipse-plugin#19]
Hey guys! I have the following setup:

MainProject
 - depends on Lib1
 - depends on Lib2
 - - depends on LibX

so MainProject references Lib1 and Lib2, while Lib2 references LibX, also in its Deployment Assembly

If I specify "Deployment Assembly" for MainProject like this:
 - Lib1
 - Lib2

I get a NullPointerException when deploying:

> !ENTRY org.eclipse.wst.server.core 4 0 2019-12-11 03:01:52.904
> !MESSAGE Could not publish to the server.
> !STACK 0
> java.lang.NullPointerException
> 	at java.io.FileInputStream.<init>(Unknown Source)
> 	at org.eclipse.jst.server.generic.core.internal.publishers.ModulePackager.write(ModulePackager.java:140)
> 	at org.eclipse.payara.tools.server.archives.AssembleModules.doPackModule(AssembleModules.java:181)
> 	at org.eclipse.payara.tools.server.archives.AssembleModules.packModule(AssembleModules.java:144)
> 	at org.eclipse.payara.tools.server.archives.AssembleModules.assembleWebModule(AssembleModules.java:109)
> 	at org.eclipse.payara.tools.server.deploying.PayaraServerBehaviour.publishDeployedDirectory(PayaraServerBehaviour.java:636)
> 	at org.eclipse.payara.tools.server.deploying.PayaraServerBehaviour.publishModuleForPayara(PayaraServerBehaviour.java:548)
> 	at org.eclipse.payara.tools.server.deploying.PayaraServerBehaviour.publishModule(PayaraServerBehaviour.java:252)
> 	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModule(ServerBehaviourDelegate.java:1093)
> 	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModules(ServerBehaviourDelegate.java:1185)
> 	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:989)
> 	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:776)
> 	at org.eclipse.wst.server.core.internal.Server.publishImpl(Server.java:3184)
> 	at org.eclipse.wst.server.core.internal.Server$PublishJob.run(Server.java:357)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> 

If I add LibX to MainProject's Deployment Assembly, everything works just fine.
Alternatively, I can set "deploy via .war file", then it works too.

Can you make the compiling / publication inclusion recursive, so that all indirectly referenced Projects/Libs from all directly Projects also get included?
Or throw a more clarifying exception when running into that problem?

Problem exists with Eclipse 2019-06 (JEE download) and 2019-09 (JDK only, EE modules installed later), and Payara 5.192 and 5.194. But I assume this to be more of a systematic problem, none of versions.

**Comment by jGauravGupta** [comment]
Hi @cbbravo,

Can you please share the project build type details or perhaps the sample project to reproduce.

**Comment by fturizo** [comment]
Issue abandoned by the requester, so closed.
