### ISSUE TITLE
Payara Eclipse Plugin hangs on server start

### ISSUE THREAD

**Issue by juerg-b69** [payara/ecosystem-eclipse-plugin#23]
OS: Windows 10 prof
Eclipse IDE 2019-12
Payara Server 5 (5.194)
Payara Tools Version:1.0.1.201912202010
JDK 11.0.6

On starting the server from the IDE I get: Unable to start server on time. Timeout while waiting for Payara to start. Just the server is started, without any application to deploy.

1. Payara starts, but the status within the IDE remains stopped.
2. Doubling the timeout just takes the double time until the error message pops up.
The log hangs at 52% without more messages. Of course there ist the "severe" error of certificate validity overrun, but I don't see this as the origin of the problem.
On trying to deploy the application I get:
The Eclipse plugin cannot communicate with the Payara server....
The Eclipse plugin cannot communicate with the Payara server. A Payara Server may be running on the same admin or HTTP port, but with a different root installation.Please also check for antivirus software, firewall configuration, or VPN setup which might block some ports.
3. As the server doesn't change status it's not possible to stop it from within the IDE.
This happens with JDK 11 (I guess JDK9 and higher)! (oracle)
The issue doesn't happen with JDK 8, when JAVA_HOME is set accordingly as well as PATH points to jdk 8.

Note: The server starts anyway, though not shown within eclipse and can be managed from the admin console of the browser as expected.

**Comment by OndroMih** [comment]
Some more info in the forum at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/payara-forum/k-xW9M7ex7s/34DCwW7ZAQAJ:

> This happens with JDK11 only, but without exception! With JDK 8 it works as expected!

**Comment by AleksNo** [comment]
Hi, exactly the same issue here. The problem is, the newest Eclipse release requires Java 11. It is not an optimal situation now. 👍 

Cheers

**Comment by pbtura** [comment]
Any progress on this? I'm running into the same problem on Ubuntu 18.04, but I get the issue with JDK 8 as well. Very frustrating.

**Comment by AleksNo** [comment]
Hi, the newest release (Version 1.2) fixed this issue for me. I can start and stop the Payara server from Eclipse Ide even with JDK 11. But it has to be the JDK. With the Adoptopenjdk JRE 11 it doesnt't work.

Cheers and thanks.

**Comment by fturizo** [comment]
No longer an issue
