### ISSUE TITLE
Payaratools 1.1 on Eclipse 2020-09 not adding Classpath Libraries

### ISSUE THREAD

**Issue by tkernstock** [payara/ecosystem-eclipse-plugin#28]
Hi,

I installed the new Eclipse 2020-09 and run it on Azul JDK 11 (also tried 15).

When I create a new project and add a Payara runtime as project facet, the "Payara System libraries"  are added to my class path as expected.
Importing a project I created with eclipse 2020-06 doesn't. When I look at the "Java Build Path" I can see the entry "Payara System Libraries" but there are no jars listed.

When I remove the Runtime and readd it, the entry is gone completely and I find the following errorlog entries:

eclipse.buildId=4.17.0.I20200902-1800
java.version=11.0.8
java.vendor=Azul Systems, Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_AT
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.core.expressions
Error
Wed Sep 23 18:13:01 CEST 2020
No property tester contributes a property org.eclipse.payara.tools.internal.containsRuntimeComponentType to type class org.eclipse.wst.common.project.facet.core.runtime.internal.BridgedRuntime

Of course a can add all the jars in the payara module folder to get my project up and running, but I would feel a lot better if the needed jars a getting added correctly by the tool itself.

Pls. find the completely reduced project as attachment.:
[CommonPersistanceAndService.zip](https://github.com/payara/ecosystem-eclipse-plugin/files/5278556/CommonPersistanceAndService.zip)

It is not a maven project, but you should be able to add it to a workspace in eclipse 2020-09 (installed by the eclipse installer ) 

Thanx
Thomas

**Comment by tkernstock** [comment]
I now found a workaround. It need a bit fiddeling in the eclipse configs ->
Close the project in eclipse and use explorer (or git workingtree) to
Open %workspace%\.settings\org.eclipse.wst.common.project.facet.core.xml and remove <runtime name="Payara 5.201"/>
Open %workspace%\.classpath and remove node <classpathentry kind="con" path="org.eclipse.payara.tools.lib.system">
Repopen the project and add the Payara Runtime in the Project Facets ->
Now all jars are added to the classpath!

This works but seems not a "clean" upgrade solution!

**Comment by fturizo** [comment]
No longer an issue
